---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: list space
    efficientip:
      ipam_server: server.mydomain.com
      username: dummyusername
      password: dummypassword
      space: LIST

  - name: list subnet of a space
    efficientip:
      ipam_server: server.mydomain.com
      username: dummyusername
      password: dummypassword
      subnet: LIST
      space: NY_space
      classparam: 'metadata1=somedata'
    register: eip

  - name: find one free IP address on a subnet
    efficientip:
      ipam_server: server.mydomain.com
      username: dummyusername
      password: dummypassword
      hostaddr: FIND_FREE
      subnet_id: 4
    register: eip

  - name: add IP on space
    efficientip:
      ipam_server: server.mydomain.com
      username: dummyusername
      password: dummypassword
      type: A
      state: present
      space: NY_space
      record: test.mydomain.com
      hostaddr: '{{ eip.result.output }}'

  - name: delete IP address
    efficientip:
      ipam_server: server.mydomain.com
      username: dummyusername
      password: dummypassword
      type: A
      state: absent
      space: NY_space
      hostaddr: 127.0.0.1

  - name: add CNAME
    efficientip:
      ipam_server: server.mydomain.com
      username: dummyusername
      password: dummypassword
      type: CNAME
      state: present
      alias_fqdn: alias.mydomain.net
      alias_value: hostname.mydomain.net
      alias_ttl: 600

  - name: delete CNAME
    efficientip:
      ipam_server: server.mydomain.com
      username: dummyusername
      password: dummypassword
      type: CNAME
      state: absent
      alias_fqdn: alias.mydomain.net
      alias_value: hostname.mydomain.net
      alias_ttl: 600

